[package]
name = "proc-macro-glob-import"
version = "0.1.0"
authors = ["Anthony Ramine <nox@nox.paris>"]
edition = "2018"
publish = false

[dependencies]
macros = { path = "macros" }
settings = { path  = "settings" }

[workspace]
members = [
    "macros",
    "settings"
]
